title: Jacob Zamora
logo: "/images/Capture.PNG"
description: > # your text below (remove <br> elements if you don't need line breaks)
  Entry-Level Data Analyst
  <br><br>
  EMail here
  <br><br>
  <a href="www.linkedin.com/in/jacob-zamora-bb6297146">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
